# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build Winlator Frost

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Setup Android SDK & NDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          ndk: 26.1.10909125
          cmake: 3.22.1

      # 4️⃣ Find gradlew and make it executable
      - name: Grant execute permission for gradlew
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
          elif [ -f "./app/gradlew" ]; then
            chmod +x ./app/gradlew
          else
            echo "❌ gradlew not found! Please ensure the Gradle wrapper exists in your repo root or /app."
            exit 1
          fi

      # 5️⃣ Build the release APK
      - name: Build Release APK
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew clean assembleRelease --stacktrace
          elif [ -f "./app/gradlew" ]; then
            cd app && ./gradlew clean assembleRelease --stacktrace
          fi

      # 6️⃣ Upload the built APK as artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Winlator-Frost-Release
          path: |
            app/build/outputs/apk/release/*.apk
            **/build/outputs/apk/release/*.apk

  # Optional second job: attach APK to GitHub Release
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/*.apk
            **/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
